apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: openshift-cluster-settings
  namespace: rhacm-policies
spec:
  description: Cluster-wide settings such as the console banner
  policies:
    - day2-console-banner
