apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: disable-self-provisioner-platform-ops
  namespace: platform-ops
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: remove-cr-self-provisioner-platform-ops
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: self-provisioner
                  annotations:
                    rbac.authorization.kubernetes.io/autoupdate: "false"
                rules: []
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: disable-self-provisioner-platform-ops
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: self-provisioners
                  annotations:
                    rbac.authorization.kubernetes.io/autoupdate: "false"
                subjects: []
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: self-provisioner
          remediationAction: enforce
          severity: high
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policies-for-dev-placement
  namespace: platform-ops
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - platform-ops
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - dev
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policies-for-dev-placement
  namespace: platform-ops
placementRef:
  name: policies-for-dev-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: disable-self-provisioner-platform-ops
    apiGroup: policy.open-cluster-management.io
    kind: Policy
