apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: baseline-infrastructure
  namespace: rhacm-policies
spec:
  description: Infra machine config pool; ingress, monitoring and image registry on infra nodes when present
  policies:
  - day2-image-registry-infra
  - day2-infra-machineconfigpool
  - day2-ingress-infra
  - day2-monitoring-infra
